/* Generated from the round 5b measurement (scratchpad sfx/audition.json): the shortlisted
   candidates per slot, the shipped default first. Tone is the processed file's spectral
   centroid: warm under 2.5 kHz, mid under 4.5 kHz, bright above. Files live in public/site/sound/audition/. */
import type { Slot } from "./sound";

export type Candidate = {
  file: string;
  label: string;
  source: string;
  feel: string;
  ms: number | null;
  lufs: number | null;
};

export const DEFAULTS: Record<Slot, string> = {
  tap: "m-ui-click-30",
  send: "m-ui-click-12",
  approve: "k-switch_006",
  stamp: "m-ui-click-25",
  toggle: "k-switch_007",
  land: "m-ui-click-14",
};

export const SLOT_INFO: Record<Slot, { title: string; where: string }> = {
  tap: {
    title: "Tap",
    where: "Tabs and pickers across the page",
  },
  send: {
    title: "Send",
    where: "A receipt tapped in the hero's phone",
  },
  approve: {
    title: "Approve",
    where: "Dana's Approve and Return on the desk",
  },
  stamp: {
    title: "Stamp",
    where: "Approving the compiled policy",
  },
  toggle: {
    title: "Toggle",
    where: "The sound switch in the nav",
  },
  land: {
    title: "Land",
    where: "The hero's charge landing, booked from the receipt click",
  },
};

export const CANDIDATES: Record<Slot, Candidate[]> = {
  tap: [
    {
      file: "m-ui-click-30",
      label: "SFXMint ui-click-30",
      source: "sfxmint.com, ui-click-30.mp3, CC0",
      feel: "single click, mid",
      ms: 42,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-27",
      label: "SFXMint ui-click-27",
      source: "sfxmint.com, ui-click-27.mp3, CC0",
      feel: "single click, mid",
      ms: 42,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-03",
      label: "SFXMint ui-click-03",
      source: "sfxmint.com, ui-click-03.mp3, CC0",
      feel: "single click, mid",
      ms: 65,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-10",
      label: "SFXMint ui-click-10",
      source: "sfxmint.com, ui-click-10.mp3, CC0",
      feel: "single click, bright",
      ms: 57,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-28",
      label: "SFXMint ui-click-28",
      source: "sfxmint.com, ui-click-28.mp3, CC0",
      feel: "click and release, mid",
      ms: 76,
      lufs: -22.0,
    },
    {
      file: "k-click_002",
      label: "Kenney click_002",
      source: "Kenney Interface Sounds 1.0, Audio/click_002.ogg, CC0",
      feel: "single click, warm",
      ms: 11,
      lufs: -22.0,
    },
    {
      file: "k-select_001",
      label: "Kenney select_001",
      source: "Kenney Interface Sounds 1.0, Audio/select_001.ogg, CC0",
      feel: "single click, mid",
      ms: 37,
      lufs: -22.0,
    },
    {
      file: "el-click",
      label: "ElevenLabs click (round 5)",
      source:
        "ElevenLabs sound effects, generated 2026-09-22 (paid plan, commercial use)",
      feel: "the round 5 generated sound",
      ms: null,
      lufs: null,
    },
  ],
  send: [
    {
      file: "m-ui-click-12",
      label: "SFXMint ui-click-12",
      source: "sfxmint.com, ui-click-12.mp3, CC0",
      feel: "click with body, warm",
      ms: 224,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-18",
      label: "SFXMint ui-click-18",
      source: "sfxmint.com, ui-click-18.mp3, CC0",
      feel: "single click, mid",
      ms: 160,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-14",
      label: "SFXMint ui-click-14",
      source: "sfxmint.com, ui-click-14.mp3, CC0",
      feel: "click and release, mid",
      ms: 139,
      lufs: -24.1,
    },
    {
      file: "m-ui-click-06",
      label: "SFXMint ui-click-06",
      source: "sfxmint.com, ui-click-06.mp3, CC0",
      feel: "click and release, mid",
      ms: 255,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-23",
      label: "SFXMint ui-click-23",
      source: "sfxmint.com, ui-click-23.mp3, CC0",
      feel: "click with body, mid",
      ms: 261,
      lufs: -24.0,
    },
    {
      file: "k-click_001",
      label: "Kenney click_001",
      source: "Kenney Interface Sounds 1.0, Audio/click_001.ogg, CC0",
      feel: "single click, mid",
      ms: 97,
      lufs: -26.0,
    },
    {
      file: "k-select_002",
      label: "Kenney select_002",
      source: "Kenney Interface Sounds 1.0, Audio/select_002.ogg, CC0",
      feel: "single click, warm",
      ms: 40,
      lufs: -22.0,
    },
    {
      file: "el-click",
      label: "ElevenLabs click (round 5)",
      source:
        "ElevenLabs sound effects, generated 2026-09-22 (paid plan, commercial use)",
      feel: "the round 5 generated sound",
      ms: null,
      lufs: null,
    },
  ],
  approve: [
    {
      file: "k-switch_006",
      label: "Kenney switch_006",
      source: "Kenney Interface Sounds 1.0, Audio/switch_006.ogg, CC0",
      feel: "click and release, warm",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-21",
      label: "SFXMint ui-click-21",
      source: "sfxmint.com, ui-click-21.mp3, CC0",
      feel: "click and release, bright",
      ms: 151,
      lufs: -24.1,
    },
    {
      file: "k-switch_002",
      label: "Kenney switch_002",
      source: "Kenney Interface Sounds 1.0, Audio/switch_002.ogg, CC0",
      feel: "click and release, warm",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-28",
      label: "SFXMint ui-click-28",
      source: "sfxmint.com, ui-click-28.mp3, CC0",
      feel: "click and release, mid",
      ms: 76,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-08",
      label: "SFXMint ui-click-08",
      source: "sfxmint.com, ui-click-08.mp3, CC0",
      feel: "single click, mid",
      ms: 41,
      lufs: -22.0,
    },
    {
      file: "k-switch_004",
      label: "Kenney switch_004",
      source: "Kenney Interface Sounds 1.0, Audio/switch_004.ogg, CC0",
      feel: "click and release, mid",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-12",
      label: "SFXMint ui-click-12",
      source: "sfxmint.com, ui-click-12.mp3, CC0",
      feel: "click with body, warm",
      ms: 224,
      lufs: -24.0,
    },
    {
      file: "el-tick",
      label: "ElevenLabs tick (round 5)",
      source:
        "ElevenLabs sound effects, generated 2026-09-22 (paid plan, commercial use)",
      feel: "the round 5 generated sound",
      ms: null,
      lufs: null,
    },
  ],
  stamp: [
    {
      file: "m-ui-click-25",
      label: "SFXMint ui-click-25",
      source: "sfxmint.com, ui-click-25.mp3, CC0",
      feel: "click and release, warm",
      ms: 261,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-24",
      label: "SFXMint ui-click-24",
      source: "sfxmint.com, ui-click-24.mp3, CC0",
      feel: "click with body, warm",
      ms: 229,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-11",
      label: "SFXMint ui-click-11",
      source: "sfxmint.com, ui-click-11.mp3, CC0",
      feel: "click with body, mid",
      ms: 209,
      lufs: -24.0,
    },
    {
      file: "k-switch_002",
      label: "Kenney switch_002",
      source: "Kenney Interface Sounds 1.0, Audio/switch_002.ogg, CC0",
      feel: "click and release, warm",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-12",
      label: "SFXMint ui-click-12",
      source: "sfxmint.com, ui-click-12.mp3, CC0",
      feel: "click with body, warm",
      ms: 224,
      lufs: -24.0,
    },
    {
      file: "k-click_005",
      label: "Kenney click_005",
      source: "Kenney Interface Sounds 1.0, Audio/click_005.ogg, CC0",
      feel: "single click, warm",
      ms: 7,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-23",
      label: "SFXMint ui-click-23",
      source: "sfxmint.com, ui-click-23.mp3, CC0",
      feel: "click with body, mid",
      ms: 261,
      lufs: -24.0,
    },
    {
      file: "el-stamp",
      label: "ElevenLabs stamp (round 5)",
      source:
        "ElevenLabs sound effects, generated 2026-09-22 (paid plan, commercial use)",
      feel: "the round 5 generated sound",
      ms: null,
      lufs: null,
    },
  ],
  toggle: [
    {
      file: "k-switch_007",
      label: "Kenney switch_007",
      source: "Kenney Interface Sounds 1.0, Audio/switch_007.ogg, CC0",
      feel: "click and release, warm",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "k-switch_006",
      label: "Kenney switch_006",
      source: "Kenney Interface Sounds 1.0, Audio/switch_006.ogg, CC0",
      feel: "click and release, warm",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "k-switch_004",
      label: "Kenney switch_004",
      source: "Kenney Interface Sounds 1.0, Audio/switch_004.ogg, CC0",
      feel: "click and release, mid",
      ms: 147,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-08",
      label: "SFXMint ui-click-08",
      source: "sfxmint.com, ui-click-08.mp3, CC0",
      feel: "single click, mid",
      ms: 41,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-29",
      label: "SFXMint ui-click-29",
      source: "sfxmint.com, ui-click-29.mp3, CC0",
      feel: "single click, bright",
      ms: 29,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-21",
      label: "SFXMint ui-click-21",
      source: "sfxmint.com, ui-click-21.mp3, CC0",
      feel: "click and release, bright",
      ms: 151,
      lufs: -24.1,
    },
    {
      file: "m-ui-click-30",
      label: "SFXMint ui-click-30",
      source: "sfxmint.com, ui-click-30.mp3, CC0",
      feel: "single click, mid",
      ms: 42,
      lufs: -22.0,
    },
    {
      file: "el-click",
      label: "ElevenLabs click (round 5)",
      source:
        "ElevenLabs sound effects, generated 2026-09-22 (paid plan, commercial use)",
      feel: "the round 5 generated sound",
      ms: null,
      lufs: null,
    },
  ],
  land: [
    {
      file: "m-ui-click-14",
      label: "SFXMint ui-click-14",
      source: "sfxmint.com, ui-click-14.mp3, CC0",
      feel: "click and release, mid",
      ms: 139,
      lufs: -24.1,
    },
    {
      file: "m-ui-click-18",
      label: "SFXMint ui-click-18",
      source: "sfxmint.com, ui-click-18.mp3, CC0",
      feel: "single click, mid",
      ms: 160,
      lufs: -24.0,
    },
    {
      file: "k-select_002",
      label: "Kenney select_002",
      source: "Kenney Interface Sounds 1.0, Audio/select_002.ogg, CC0",
      feel: "single click, warm",
      ms: 40,
      lufs: -22.0,
    },
    {
      file: "m-ui-click-06",
      label: "SFXMint ui-click-06",
      source: "sfxmint.com, ui-click-06.mp3, CC0",
      feel: "click and release, mid",
      ms: 255,
      lufs: -24.0,
    },
    {
      file: "m-ui-click-25",
      label: "SFXMint ui-click-25",
      source: "sfxmint.com, ui-click-25.mp3, CC0",
      feel: "click and release, warm",
      ms: 261,
      lufs: -24.0,
    },
    {
      file: "k-click_002",
      label: "Kenney click_002",
      source: "Kenney Interface Sounds 1.0, Audio/click_002.ogg, CC0",
      feel: "single click, warm",
      ms: 11,
      lufs: -22.0,
    },
    {
      file: "el-card",
      label: "ElevenLabs card (round 5)",
      source:
        "ElevenLabs sound effects, generated 2026-09-22 (paid plan, commercial use)",
      feel: "the round 5 generated sound",
      ms: null,
      lufs: null,
    },
  ],
};
